2023 Q1 Tweaks
InfosecForActivistsTeam/infosec-activists pull request #34
Opened 2023-08-30 23:17 UTC by bskinner

Minor tweaking to the wording in the iPhone section.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +**Bluetooth, WiFi, and Ultrawideband (UWB)** are common technologies that use short-range radios to communicate with
Mentioned UWB here since that is a wireless technology present in the last several generations of phones.

I'd be open to removing this piece since it's not explicitly mentioned within the OS, but it is toggled by the Airplane mode functionality.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +enforcement. [Some police departments](https://www.aclu.org/issues/privacy-technology/surveillance-technologies/stingray-tracking-devices-whos-got-them) also have access to devices known
It's an older article, but I haven't seen any updates from EFF. Considering it still relevant since there hasn't been any explicit ban on Stingray devices, and they've gone through several generations at this point.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +radio and some, or all, of the other radios present on the device. The exact behavior is dependent on
iOS doesn't disable _all_ radios initially by default, and the user need to manually disable Bluetooth for the device to disable it the next time Airplane mode is used. The intent here was to explicitly call out this behavior to the reader.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +unless you are actively sharing files with someone.
No content changes, just whitespace

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +device instead of *Face ID* where it is referenced below.
There is only a single device in Apple's supported devices which has Touch ID so Face ID should be the primary biometric method.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +	* *Settings → General → AirDrop*, tap on **Receiving Off**
Use "tap" vs "select" to be more in-line with the interaction mechanics

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +	* Bluetooth **will not** be disabled the first time you use Airplace Mode. If you disable
Add a note about the bluetooth behavior! Bluetooth is no longer disabled in airplane mode unless the user explicitly disables it.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +	* *Settings → Bluetooth*, toggle the *Bluetooth* slider off.
Keep "toggle" (and update the "tap" wording above), or move this to "tap"? I dislike using two different phrases for similar actions.

2023-08-30 23:30 UTC, bskinner commented on content/en/_index.md
> +	* Practice with iOS’ [Emergency SOS](https://support.apple.com/en-us/HT208076) mode, and
Link to the emergency SOS docs

2023-08-30 23:30 UTC, bskinner commented on go.mod
> +require github.com/alex-shpak/hugo-book v0.0.0-20230213220505-036e037a63ba // indirect
Module updates

2023-08-30 23:30 UTC, bskinner commented on go.sum
> +github.com/alex-shpak/hugo-book v0.0.0-20230213220505-036e037a63ba/go.mod h1:L4NMyzbn15fpLIpmmtDg9ZFFyTZzw87/lk7M2bMQ7ds=
Module updates

2023-08-30 23:45 UTC, marksherman requested changes

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +**Bluetooth, WiFi, and Ultrawideband (UWB)** are common technologies that use short-range radios to communicate with
Excellent. Anyone with this degree of concern should know that this technology *exists* and is actively in use.

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +other devices. Unfortunately, their operation requires your phone to broadcast information which can uniquely itself. This information can be observed by a "beacon" or scanning device.
uniquely what itself
```suggestion
other devices. Unfortunately, their operation requires your phone to broadcast information which can uniquely identify itself. This information can be observed by a "beacon" or scanning device.
```

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +enforcement. [Some police departments](https://www.aclu.org/issues/privacy-technology/surveillance-technologies/stingray-tracking-devices-whos-got-them) also have access to devices known
👍

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +as cell site simulators, IMSI catchers, or a "Stingray". These devices can mimic a cellular tower,
the names changing plurality is a tad strange but I see that as the better side of making the sentence more contrived to avoid it. This wording isn't perfect grammar but ease of understanding is more important, so I approve

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +as cell site simulators, IMSI catchers, or a "Stingray". These devices can mimic a cellular tower,
Though if anyone has a better sentence suggestion, it could be helpful! @drewbjorn

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +as cell site simulators, IMSI catchers, or a "Stingray". These devices can mimic a cellular tower,
"cellular" is a distinctly American term. "Cell phone" does not cross oceans. Where this specific use of the word is about towers, which are already more of a conceptual stretch for a "normal person," I recommend we generalize the phrasing here.
```suggestion
as cell site simulators, IMSI catchers, or a "Stingray". These devices can mimic a mobile phone tower,
```

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +and provide the police with not only more accurate, but real-time, data.
```suggestion
and provide the police with more accurate, real-time data.
```

2023-08-30 23:45 UTC, marksherman commented on content/en/_index.md
> +device instead of *Face ID* where it is referenced below.
Remember activists are often working with many-generations-outdated tech, including phones that have long fell off the manufacturer's support lists. App Inventor saw OVER TEN year old android phones in regular use in their telemetry.

2023-08-30 23:49 UTC, bskinner commented on content/en/_index.md
> +device instead of *Face ID* where it is referenced below.
Resolved via parallel conversation- the text as-is in this PR is fine.

2023-08-30 23:53 UTC, bskinner commented on content/en/_index.md
> +as cell site simulators, IMSI catchers, or a "Stingray". These devices can mimic a cellular tower,
> the names changing plurality is a tad strange but I see that as the better side of making the sentence more contrived to avoid it. This wording isn't perfect grammar but ease of understanding is more important, so I approve

Agreed- it was weird and I couldn't find a good rewrite after a lot of linguistic gymnastics. If someone has a better wording, I'm all for it!

2023-08-31 00:06 UTC, marksherman approved these changes

2023-08-31 00:06 UTC, merged